In [1]:
a = [1,2,3,4]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [9]:
aa = (1:2:5)
println(aa.start)
println(aa.step)
println(aa.stop)
println(first(aa))
println(step(aa))
println(last(aa))

1
2
5
1
2
5


In [11]:
Int8[3,4,5]

3-element Array{Int8,1}:
 3
 4
 5

In [12]:
["one", "two", "three"]

3-element Array{String,1}:
 "one"
 "two"
 "three"

In [13]:
[true, "two", 1, 2.0]

4-element Array{Any,1}:
 true
     "two"
    1
    2.0

In [16]:
[]

Any[]

In [15]:
Int8[]

Int8[]

In [17]:
a = (1,2,3)
b = collect(a)

3-element Array{Int64,1}:
 1
 2
 3

In [22]:
c = collect(1:4)  # 不能直接写成[1:4]，否则类型不一样，c只有一个element
c[2:end]

3-element Array{Int64,1}:
 2
 3
 4

In [24]:
c1 = c  # c1与c的内存地址相同
c2 = c[:]  # c2是c的一个拷贝
c1[1] = 10
c

4-element Array{Int64,1}:
 10
  2
  3
  4

In [25]:
c2[1] = 20
c

4-element Array{Int64,1}:
 10
  2
  3
  4

In [26]:
b = [1;2;3;4]  # 向量

4-element Array{Int64,1}:
 1
 2
 3
 4

In [27]:
c = [1 2 3 4]  # 矩阵

1×4 Array{Int64,2}:
 1  2  3  4

矩阵拼接中的`空格`，`，`，`；`的区别：

In [28]:
x = ones(2, 3)
y = zeros(2, 3)
z = [x y]  # 等同于hcat()

2×6 Array{Float64,2}:
 1.0  1.0  1.0  0.0  0.0  0.0
 1.0  1.0  1.0  0.0  0.0  0.0

In [29]:
hcat(x, y)  

2×6 Array{Float64,2}:
 1.0  1.0  1.0  0.0  0.0  0.0
 1.0  1.0  1.0  0.0  0.0  0.0

In [30]:
ndims(z)

2

In [31]:
z = [x, y]

2-element Array{Array{Float64,2},1}:
 [1.0 1.0 1.0; 1.0 1.0 1.0]
 [0.0 0.0 0.0; 0.0 0.0 0.0]

In [32]:
ndims(z)

1

In [33]:
z = [x; y]  # 等价与vcat()

4×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [34]:
vcat(x, y)

4×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [35]:
ndims(z)

2

把`[x, y]`变成一个没有嵌套的矩阵：

In [36]:
hcat([x, y]...)

2×6 Array{Float64,2}:
 1.0  1.0  1.0  0.0  0.0  0.0
 1.0  1.0  1.0  0.0  0.0  0.0

矩阵索引，从1开始：

In [42]:
z[1]

1.0

In [44]:
z[6]

1.0

In [45]:
size(z)  # 查看维度

(4, 3)

In [48]:
length(z)  # 求Z元素个数

12

In [49]:
sum(z)  # 求Z所有元素和

6.0

#### 矩阵运算

In [51]:
a = collect(reshape(1:6, 2, 3))
b = ones(2, 3)

2×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [52]:
a .+ b  # .对元素操作

2×3 Array{Float64,2}:
 2.0  4.0  6.0
 3.0  5.0  7.0

In [53]:
a .- b

2×3 Array{Float64,2}:
 0.0  2.0  4.0
 1.0  3.0  5.0

In [55]:
a .* b

2×3 Array{Float64,2}:
 1.0  3.0  5.0
 2.0  4.0  6.0

In [56]:
a*b'

2×2 Array{Float64,2}:
  9.0   9.0
 12.0  12.0

In [57]:
a / b

2×2 Array{Float64,2}:
 1.5  1.5
 2.0  2.0

In [58]:
a ./b

2×3 Array{Float64,2}:
 1.0  3.0  5.0
 2.0  4.0  6.0

函数对矩阵操作时也要加`.`：

In [65]:
A = [1, 2, 3]
sin.(A)

3-element Array{Float64,1}:
 0.8414709848078965
 0.9092974268256817
 0.1411200080598672

针对元素的添加/删除/移动：

In [77]:
a = [1, 2, 3]
push!(a, 4)

4-element Array{Int64,1}:
 1
 2
 3
 4

In [78]:
pop!(a)

4

In [79]:
push!(a, 4,5,6)

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

In [80]:
push!(a, [7,8,9])

LoadError: MethodError: Cannot `convert` an object of type Array{Int64,1} to an object of type Int64
Closest candidates are:
  convert(::Type{T}, !Matched::T) where T<:Number at number.jl:6
  convert(::Type{T}, !Matched::Number) where T<:Number at number.jl:7
  convert(::Type{T}, !Matched::Ptr) where T<:Integer at pointer.jl:23
  ...

In [81]:
append!(a, [7,8,9])

9-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

In [82]:
prepend!(a, [10,11,12])

12-element Array{Int64,1}:
 10
 11
 12
  1
  2
  3
  4
  5
  6
  7
  8
  9

In [83]:
arr = reshape(1:6, 2, 3)

2×3 reshape(::UnitRange{Int64}, 2, 3) with eltype Int64:
 1  3  5
 2  4  6

In [84]:
circshift(arr, (0, 1))  # 横向不变，纵向向下平移1个单位

2×3 Array{Int64,2}:
 5  1  3
 6  2  4

In [87]:
circshift(arr, (1, -2))  # 横向向右平移1个单位，纵向向上平移2个单位

2×3 Array{Int64,2}:
 4  6  2
 3  5  1

#### 随机数

In [88]:
rand(10)

10-element Array{Float64,1}:
 0.8724041976208623
 0.30524669704163143
 0.7356848460730496
 0.3134957904282629
 0.09558396421625659
 0.3808031826178364
 0.032248222285851336
 0.9564161650457996
 0.1939220495334819
 0.4234755086882258

In [89]:
rand(2, 3)

2×3 Array{Float64,2}:
 0.764844   0.314525  0.146059
 0.0705314  0.567827  0.368286

In [90]:
rand(Int32, 2, 3)

2×3 Array{Int32,2}:
 -824491392  -202238290  1434724254
  385914424  -145693357  -853743838

In [91]:
reshape(1:6, (2, 3))

2×3 reshape(::UnitRange{Int64}, 2, 3) with eltype Int64:
 1  3  5
 2  4  6

In [99]:
using Statistics

LoadError: syntax: incomplete: premature end of input

3.0